<?php

function warehouse_api_menu() {
    $items['warehouse-api'] = array(
      'page callback' => 'warehouse_api_data',
      'access callback' => TRUE
    );
    return $items;
  }
  function warehouse_api_data() {

    $data = array(
        'limit' => 1,
        'filters' => array(
            "sku.AP"=> 3600
        )
    );
     
    $post_data = json_encode($data);
     
    // Prepare new cURL resource
    $crl = curl_init('http://blankstyle-backend-api-dev.us-west-2.elasticbeanstalk.com/product/query');
    curl_setopt($crl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($crl, CURLINFO_HEADER_OUT, true);
    curl_setopt($crl, CURLOPT_POST, true);
    curl_setopt($crl, CURLOPT_POSTFIELDS, $post_data);
     
    // Set HTTP Header for POST request 
    curl_setopt($crl, CURLOPT_HTTPHEADER, array(
        'Accept: application/json',
        'Content-Type: application/json',
        'x-api-key: 3f3a08b75714fafaacbef538a4ef72474d7f8189f8943d3b151f38327c274388'
    ));
     
    // Submit the POST request
    $result = curl_exec($crl);
     
    // handle curl error
    if ($result === false) {
        // throw new Exception('Curl error: ' . curl_error($crl));
        //print_r('Curl error: ' . curl_error($crl));
        $result_noti = 0; die();
    } else {
  
        $result_noti = 1; die();
    }
    // Close cURL session handle
    curl_close($crl);
  
    print "<pre>";print_r($result);
  }